name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@75a1d77169240b76e9e0bce6ea2ac33a3f7f0229 # Version updatd to use version 2.0.69 of the CxOne CLI
        with:
          additional_params: --report-format sarif
          base_uri: https://anz.ast.checkmarx.net/
          cx_tenant: cx_ps_apac_test_james_bostock
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: cx_result.sarif
