name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checkmarx One scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkmarx One scan
        uses: checkmarx/ast-github-action@2.0.44
        with:
          base_uri: https://anz.ast.checkmarx.net
          cx_tenant: ${{ secrets.CX_TENANT_NAME }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
